---
abstract: 'Lexically warn about using the indirect method call syntax.'
author:
  - 'Vincent Pit <vpit@cpan.org>'
build_requires:
  Carp: '0'
  Config: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IO::Select: '0'
  IPC::Open3: '0'
  POSIX: '0'
  Socket: '0'
  Test::More: '0'
  XSLoader: '0'
  lib: '0'
configure_requires:
  Config: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: indirect
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  XSLoader: '0'
  perl: '5.008001'
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Name=indirect
  homepage: http://search.cpan.org/dist/indirect/
  license: http://dev.perl.org/licenses/
  repository: http://git.vpit.fr/?p=perl%2Fmodules%2Findirect.git
version: '0.39'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
